# Generated by Django 4.0.5 on 2022-06-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('R', 'REJECTED'), ('S', 'SUCCESSFUL'), ('F', 'FAILED')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
