# Generated by Django 4.0.5 on 2022-07-04 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_ad',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_purchase',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_ad',
            field=models.CharField(max_length=500),
        ),
    ]
