# Generated by Django 4.0.5 on 2022-07-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_billing_ad_alter_order_date_of_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subtotal',
        ),
    ]
