# Generated by Django 4.0.5 on 2022-07-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_item_quantity_remove_item_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_no',
            field=models.CharField(max_length=14),
        ),
    ]
