# Generated by Django 4.0.5 on 2022-07-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_phone_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='OrderItem',
        ),
    ]
