# Generated by Django 4.0.5 on 2022-07-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_item_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
